### PR TITLE
Create file3.txt

### PR DESCRIPTION
**Pull request by DannyFeliz**

### CODE REVIEW

**Comment by DannyFeliz** [comment]
sss

**Review by DannyFeliz08 — DISMISSED** [review]
This is not working Y_Y

**Review by DannyFeliz08 — CHANGES_REQUESTED** [review]
this is wrong

**Review by MrFather2 — CHANGES_REQUESTED** [review]
This is bad

**Review by MrFather — CHANGES_REQUESTED** [review]
You need to fix the conflicts

**Review by MrFather — CHANGES_REQUESTED** [review]
Also fix the validation issue

**Review by MrFather — CHANGES_REQUESTED** [review]
This is not compatible with PHP 5.6

**Pull request closed without merging**
